package hunnuse.wyc.dao;

import hunnuse.wyc.dataobject.Travelogue;

import java.util.List;

public interface TravelogueMapper {
    List<Travelogue>listTravelogue();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    int deleteByPrimaryKey(Integer docId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    int insert(Travelogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    int insertSelective(Travelogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    Travelogue selectByPrimaryKey(Integer docId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    int updateByPrimaryKeySelective(Travelogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Travelogue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelogue
     *
     * @mbg.generated Sat Apr 18 11:08:42 CST 2020
     */
    int updateByPrimaryKey(Travelogue record);
}