package hunnuse.wyc.dao;

import hunnuse.wyc.dataobject.WebRuleAtt;

public interface WebRuleAttMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WebGeoNamecontent
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    int deleteByPrimaryKey(Integer webruleattid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WebGeoNamecontent
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    int insert(WebRuleAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WebGeoNamecontent
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    int insertSelective(WebRuleAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WebGeoNamecontent
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    WebRuleAtt selectByPrimaryKey(Integer webruleattid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WebGeoNamecontent
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    int updateByPrimaryKeySelective(WebRuleAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WebGeoNamecontent
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    int updateByPrimaryKey(WebRuleAtt record);
}