package hunnuse.wyc.dataobject;

public class WebGeoName {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webgeoname.WebGeonameId
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    private Integer webgeonameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webgeoname.WebGeonameContent
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    private String webgeonamecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webgeoname.Latitude
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webgeoname.Longitude
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webgeoname.Occurence
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    private Integer occurence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webgeoname.name
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webgeoname.WebGeonameId
     *
     * @return the value of webgeoname.WebGeonameId
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public Integer getWebgeonameid() {
        return webgeonameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webgeoname.WebGeonameId
     *
     * @param webgeonameid the value for webgeoname.WebGeonameId
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public void setWebgeonameid(Integer webgeonameid) {
        this.webgeonameid = webgeonameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webgeoname.WebGeonameContent
     *
     * @return the value of webgeoname.WebGeonameContent
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public String getWebgeonamecontent() {
        return webgeonamecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webgeoname.WebGeonameContent
     *
     * @param webgeonamecontent the value for webgeoname.WebGeonameContent
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public void setWebgeonamecontent(String webgeonamecontent) {
        this.webgeonamecontent = webgeonamecontent == null ? null : webgeonamecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webgeoname.Latitude
     *
     * @return the value of webgeoname.Latitude
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webgeoname.Latitude
     *
     * @param latitude the value for webgeoname.Latitude
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webgeoname.Longitude
     *
     * @return the value of webgeoname.Longitude
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webgeoname.Longitude
     *
     * @param longitude the value for webgeoname.Longitude
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webgeoname.Occurence
     *
     * @return the value of webgeoname.Occurence
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public Integer getOccurence() {
        return occurence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webgeoname.Occurence
     *
     * @param occurence the value for webgeoname.Occurence
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public void setOccurence(Integer occurence) {
        this.occurence = occurence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column webgeoname.name
     *
     * @return the value of webgeoname.name
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column webgeoname.name
     *
     * @param name the value for webgeoname.name
     *
     * @mbg.generated Tue Apr 14 18:19:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}