package hunnuse.wyc.dataobject;

public class WebRuleAtt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WebGeoNamecontent.WebRuleAttId
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    private Integer webruleattid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WebGeoNamecontent.WebRuleAttRules
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    private String webruleattrules;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WebGeoNamecontent.Occurence
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    private Integer occurence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WebGeoNamecontent.ruleSize
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    private Integer rulesize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WebGeoNamecontent.WebRuleAttId
     *
     * @return the value of WebGeoNamecontent.WebRuleAttId
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public Integer getWebruleattid() {
        return webruleattid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WebGeoNamecontent.WebRuleAttId
     *
     * @param webruleattid the value for WebGeoNamecontent.WebRuleAttId
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public void setWebruleattid(Integer webruleattid) {
        this.webruleattid = webruleattid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WebGeoNamecontent.WebRuleAttRules
     *
     * @return the value of WebGeoNamecontent.WebRuleAttRules
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public String getWebruleattrules() {
        return webruleattrules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WebGeoNamecontent.WebRuleAttRules
     *
     * @param webruleattrules the value for WebGeoNamecontent.WebRuleAttRules
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public void setWebruleattrules(String webruleattrules) {
        this.webruleattrules = webruleattrules == null ? null : webruleattrules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WebGeoNamecontent.Occurence
     *
     * @return the value of WebGeoNamecontent.Occurence
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public Integer getOccurence() {
        return occurence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WebGeoNamecontent.Occurence
     *
     * @param occurence the value for WebGeoNamecontent.Occurence
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public void setOccurence(Integer occurence) {
        this.occurence = occurence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WebGeoNamecontent.ruleSize
     *
     * @return the value of WebGeoNamecontent.ruleSize
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public Integer getRulesize() {
        return rulesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WebGeoNamecontent.ruleSize
     *
     * @param rulesize the value for WebGeoNamecontent.ruleSize
     *
     * @mbg.generated Thu Apr 09 15:37:58 CST 2020
     */
    public void setRulesize(Integer rulesize) {
        this.rulesize = rulesize;
    }
}